import{r as e}from"./assets/rolldown-runtime-hePW80VL.js";import{n as t,r as n,t as r}from"./assets/vendor-DmOZ11X9.js";(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),t.credentials=e.crossOrigin===`use-credentials`?`include`:e.crossOrigin===`anonymous`?`omit`:`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})();function i(e){return n.get(`https://pixabay.com/api/`,{params:{key:`57577580-6d8d08492b925cf635d4baae0`,q:e,image_type:`photo`,orientation:`horizontal`,safesearch:`true`}}).then(e=>e.data)}var a=e(t(),1),o=document.querySelector(`.gallery`),s=document.querySelector(`.loader`),c=new a.default.default(`.gallery a`,{captionsData:`alt`,captionDelay:250});function l(e){o.innerHTML=e.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}" class="gallery-link">
          <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${e.likes}</p>
          <p class="info-item"><b>Views</b> ${e.views}</p>
          <p class="info-item"><b>Comments</b> ${e.comments}</p>
          <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
        </div>
      </li>`).join(``),c.refresh()}function u(){o.innerHTML=``}function d(){s.classList.remove(`is-hidden`)}function f(){s.classList.add(`is-hidden`)}var p=e(r(),1),m=document.querySelector(`form`),h=document.querySelector(`input`);m.addEventListener(`submit`,e=>{e.preventDefault();let t=h.value.trim();if(t===``){p.default.error({message:`Sorry, the input is empty`,position:`topRight`});return}u(),d(),i(t).then(e=>{e.hits.length===0?p.default.error({message:`Sorry, there are no images matching your search query. Please try again!`,position:`topRight`}):l(e.hits)}).catch(e=>{p.default.error({message:`Sorry, there are no images matching your search query. Please try again!`,position:`topRight`})}).finally(()=>{f()})});
//# sourceMappingURL=index.js.map